spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop # 시작될때 drop하고 create == 종료시 drop하고 create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

mybatis:
  mapper-locations: classpath:mybatis/mapper/mysql/**/**.xml    # classpath는 ./resources를 의미함
#  type-handlers-package: com.example.darts.mapper.typehandler
  type-aliases-package: com.example.darts.domain.post.entity
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30 # 쿼리를 날렸을 때, 30초이상 걸리면 끊어라
    default-fetch-size: 100 # 한 번에 최대로 들고 올 수 있는 사이즈

logging:
  level:
    org.hibernate.SQL: debug